### ISSUE TITLE
[Feat] Spring boot version Migration

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#1]
## **Issue : Feature**

- 스프링 부트의 버전을 마이그레이션 한다.

## **Description**

- Spring boot version : 2.7.x → 3.2.x
- Java version : 11 → 17
- Swagger : springfox → springdoc

## **Todo**

- [x] Spring Boot 버전 업그레이드
- [x] Java 버전 업그레이드
- [x] Swagger 변경
- [x] javax 에서 jakarta로 변경

## **Reference(Optional)**

[참고 자료]
- [Spring Boot 3.0 Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide)
