### ISSUE TITLE
[Bug] 이미지 저장 로직 수정

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#101]
## Type of change

- [x] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

그룹 생성 - 커버 이미지를 넣어도 그룹 조회하면 기본 이미지로 오는 오류 있음
모임 기록 활동 추가 - 모임 활동 텍스트와 정산은 들어가는데, 이미지는 아예 안 들어가는 오류 있음

## **Todo**

- [x] 그룹 생성 이미지 문제 해결
- [x] 모임 기록 활동 추가 이미지 문제 해결
