### ISSUE TITLE
[Bug] 스웨거 test 환경 구축

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#103]
## Type of change

- [x] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [x] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

1. Swagger 문서 내에서 Jwt 토큰 사용해 test를 진행할 수 있도록 구성
2. Swagger 문서 내에서 multipart/form-data requset test를 진행할 수 있도록 구성

## **Todo**

- [ ] jwt 로직 수정
- [ ] multipart/form-data test 환경 구축
- [ ] swagger api test 진행
