### ISSUE TITLE
[Document] 요구사항에 따른 스웨거 설명 수정

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#105]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [x] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

공통
-  전체적으로 파라미터 역할, 값에 대한 설명이 추가되면 좋을 것 같습니다. (Ex. 3 개인 일정 삭제 API의 kind)

Auth
- API 설명이 회원가입은 naver, apple로, 회원탈퇴는 네이버, 애플로 되어있음

Diary (그룹)
- Diary ('그룹') -> ('모임')으로 변경
- '장소'로 되어있는 설명 '활동'으로 고치기
- 모임 기록 생성 API -> 모임 기록 활동 추가 API + money request part로 변경
- 모임 기록 텍스트 추가 -> 모임 기록에 대한 개인의 메모 추가 (조금 긴 느낌이 있으니 펼쳤을 때 나오는 설명에서 보이면 좋을 듯함)

## **Todo**

- [x] 공통 설명 변경
- [x] Auth 설명 변경
- [x] Diary 설명 변경
