### ISSUE TITLE
[Feature] 모임 기록 삭제(그룹) api 파라미터 변경

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#112]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- moimDiaryId를 클라이언트 측에서 구하기 힘듬으로 moimScheduleId로 변경해주길 요청 받음 

## **Todo**

- [x] 파라미터 수정
- [x] 파라미터 수정에 따른 로직 수정
