### ISSUE TITLE
[Fix] 월간 기록 조회 500 에러

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#115]
## Type of change

- [x] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

월간 기록 조회 500번 에러 발생 이유 확인 및 해결

## **Todo**

- [ ] 에러 발생 원인 확인
- [ ] 이슈 해결 진행
