### ISSUE TITLE
[Feat] 모임 기록 개별 조회 api 개발

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#117]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

모임 기록에 대한 상세 정보를 개별 조회 하는 api 추가

## **Todo**

- [x] api 구축

**Comment by luke0408** [comment]
모임 기록 개별 조회 (그룹)을 사용하는 것으로 대체
