### ISSUE TITLE
[Feat] 개인이 삭제한 모임 일정 표기 관련 로직 수정

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#120]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

[예시 상황]
- A 그룹에서 모임 일정을 추가함
- 이후 개인 일정에서 A 그룹이 생성한 모임 일정을 삭제함
- 이때 삭제한 모임 일정은 B 그룹에서도 보이면 안됨 (하지만 지금은 보이고 있음)

## **Todo**

- [ ] 개인이 삭제한 모임 일정이 표기 되지 않도록 수정
