### ISSUE TITLE
[Refactor] 멀티모듈 적용

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#134]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [x] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 코드 수정시에 변경이 어려운 부분들을 확인하게 되어 아래와 같은 모습으로 변경하고자함. (자세한 내용은 notion에 정리)
<img width="1042" alt="image" src="https://github.com/Namo-log/Server/assets/98688494/c1b6656b-38c7-420d-8ca3-238a9953b7e6">

## **Todo**

- [x] Common 모듈 분리
- [x] 독립 모듈 분리
- [x] Client 모듈 분리
- [x] #135
- [x] Api 모듈 분리
- [x] #136
