### ISSUE TITLE
[Refactor] Domain과 Api 모듈 분리

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#135]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- #134 이슈에서 domain 분리 작업량이 크다는 것을 느껴 몇가지 task로 분리함
- 해당 이슈에서는 Domain 계층과 Service 계층 간의 의존성 분리를 진행함

[ 진행 내용 ]
1. 불필요한 DTO 참조 제거 ex) QueryDSL에서 request DTO를 참조하는 상황 제거
  i. DTO를 사용해야하는 상황일시 Domain 계층에서 사용할 DTO를 추가적으로 구현하고 비니지스 레이어에서 Converter를 통해 해당 DTO를 수정해 사용하는 것으로함.
  ii. 또한 DTO를 알려주는 것이 아니라 도메인이 이미 알고 있는 개념의 형태로 변환하여 외부의 요구사항에 의해 내부 로직이 결정되지 않도록 한다.
2. interface를 활용한 계층간 의존성 분리

## **Todo**

- [ ] 비지니스 레이어와 도메인 레이어의 의존성 분리
