### ISSUE TITLE
[Document] README 문서 최신화

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#136]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [x] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 분리된 각 모듈 및 root Project에 대한 README 최신화

## **Todo**

- [x] application 글 모듈 작성
- [x] clients 글 모듈 작성
- [x] core 글 모듈 작성
- [x] storage 글 모듈 작성
- [x] support 글 모듈 작성
- [x] root Project 글 작성
