### ISSUE TITLE
[Refactor] dto 네이밍 규칙 적용

### ISSUE THREAD

**Issue by hyeonji91** [Namo-Mongmong/Server#166]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

dto 네이밍 규칙 적용
controller단에서 모임 그룹 워딩 분리

## **Todo**

- [ ] dto
- [ ] controller
