### ISSUE TITLE
[Feature] api 버저닝을 위한 전략패턴 interface 구현

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#173]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

api 버전업을 진행하기전에 우선 버저닝 작업을 위한 전략패턴 작업을 진행하고자 합니다.

## **Todo**

- [ ] facade 인터페이스 구현
- [ ] facade에 대한 전략 패턴적용
