### ISSUE TITLE
[Feature] 기록 이미지 개별 삭제 기능 구현

### ISSUE THREAD

**Issue by hosung-222** [Namo-Mongmong/Server#174]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

개별 이미지 삭제를 위한 API 구현

## **Todo**

- [ ] 이미지 삭제 API 작성
- [ ] Test
