### ISSUE TITLE
[Feature] DB 스키마 수정 대비를 위한 storage 모듈 추가

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#175]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

DB 스키마 및 내부 동작에 대한 수정을 용이하게 하기 위해서 미리 모듈을 추가한다

## **Todo**

- [ ] db-mysql-v2 모듈 세팅
