### ISSUE TITLE
[Feature] 테이블 구조 변경에 따른 API 수정을 위한 모듈 추가

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#177]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
DB 구조 변경에 따른 API 수정 혹은 교체 작업을 위하여 API v2 모듈을 추가합니다.

## **Todo**
- [x] API V2 모듈 추가
