### ISSUE TITLE
[Refactor] 개인 일정 기록 전체 조회 Response 리팩토링

### ISSUE THREAD

**Issue by hosung-222** [Namo-Mongmong/Server#184]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [X] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 개인 일정 기록 이미지에 대해 ID, URL 쌍으로 반환하도록 Response DTO 수정

## **Todo**

- [ ] Res DTO 수정
- [ ] builder 수정
