### ISSUE TITLE
[Feature] 그룹 참여/조회/수정/탈퇴 API V2구현

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#186]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
개정된 스키마 구조를 적용하여 기존의 그룹 생성/참여/조회/수정/탈퇴 API를 구현합니다.

## **Todo**
- [ ] 그룹 참여 API 구현
- [ ] 그룹 조회 API 구현
- [ ] 그룹 수정 API 구현
- [ ] 그룹 탈퇴 API 구현
