### ISSUE TITLE
[Feature] 그룹 생성 API V2구현

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#187]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
그룹 생성 API를 구현합니다.

- 요구 사항 
![image](https://github.com/user-attachments/assets/84b3f749-12f9-4921-ae94-a2ae510b0234)
  - 그룹 생성 시, `그룹 이름`, `그룹 프로필 이미지`를 클라이언트에게 전달 받습니다.
  - 이후 `그룹 코드`를 서버 내부에서 생성하여 클라이언트에게 전달 받은 데이터와 함께 그룹 테이블에 저장합니다.
    - 그룹을 생성한 `유저의 정보`와 함께 유저에 대한 `color`을 그룹-유저 매핑 테이블에 저장합니다.
    - 해당 color는 팔레트의 10가지 색상 중 하나여야합니다.
    - 해당 데이터가 쓰이는 화면
             <img width="212" alt="image" src="https://github.com/user-attachments/assets/0aaf1bb9-fc12-4fd0-b10a-4665e8a9ae11">
   

## **Discussion**
  - 그룹 프로필 이미지
    - 현재 v1에서는 이미지를 서버에서 받아오는 로직인데, 클라이언트 로컬 스토리지에서 처리를 하지 않는 이유가 궁금합니다.
   

  - 그룹 코드 생성 
     <img width="307" alt="image" src="https://github.com/user-attachments/assets/84ecec27-0ad5-4e9e-a24e-f3d6f3ccbc99">
    - v1 에서는 사진과 같이 불필요하게 긴 코드가 저장되고 있습니다.
    - PM분과 참여 코드 정책에 대해 테이블에 저장하는 정적 데이터가 아닌 ,일정 시간이 지나면 사용할 수 없는 `일회용 코드`로 수정하는 방향으로 논의하였습니다.
    -> 이런식으로 수정 된다면 code 컬럼을 삭제하고, redis에 해당 데이터를 저장하는 방식으로 변경해야할 것 같습니다.
    -> 또한 프론트와 ui도 수정되어야 할것 같아 이에 대한 정책이 확정된 후 구현해야합니다.
   

  - 그룹원 컬러 지정
      <img width="758" alt="image" src="https://github.com/user-attachments/assets/57f6c6e2-257d-44cb-b86d-1c3926008a76">
      ```
      // GroupFacade.java
      private int selectColor(Moim group) {
		      Set<Integer> colors = group.getMoimAndUsers()
			      .stream()
			      .map(MoimAndUser::getColor)
			      .collect(Collectors.toSet());
		      return Arrays.stream(GROUP_USERS_COLOR)
			      .filter((color) -> !colors.contains(color))
			      .findFirst()
			      .orElseThrow(() -> new GroupException(ErrorStatus.NOT_FOUND_COLOR));
	      }
      ```
    - v1 스키마의 경우 `moim_and_user` 테이블의 `color` 컬럼에 그룹원 고유의 색상을 저장합니다. 
      - 이 `color` 컬럼은 palette 테이블을 참조하고 있지 않지만, palette 테이블에 있는 pk 값만(5~14) 저장되도록 구현되어있습니다.
      -  v2 스키마에는 해당 컬럼이 빠져있는 상태
 
     - v2 에서의 구현 방향 논의
       - palette 테이블 개선
         - 추후 추가 기능 및 동기화를 위해 해당 테이블이 필요하다고 보여집니다.
         - `belong`과 `color` 컬럼의 의미가 불분명하다고 생각되어 개선이 필요하다고 생각합니다.
         - 또한 palette 테이블의 변동성에 따라 enum class를 구현할지에 대한 고려해야 할 것 같습니다.
        - 그룹원 컬러 지정 로직
          - 기존의 정적 배열 사용하는 방식 or enum class를 구현하여 사용 
 
## **Todo**

- [ ] 그룹 생성 API 구현

**Comment by luke0408** [comment]
>   * v1 스키마의 경우 `moim_and_user` 테이블의 `color` 컬럼에 그룹원 고유의 색상을 저장합니다.
>     
>     * 이 `color` 컬럼은 palette 테이블을 참조하고 있지 않지만, palette 테이블에 있는 pk 값만(5~14) 저장되도록 구현되어있습니다.
>     * v2 스키마에는 해당 컬럼이 빠져있는 상태
>   * v2에서의 구현 방향 논의
>     
>     * palette 테이블 개선
>       
>       * 추후 추가 기능 및 동기화를 위해 해당 테이블이 필요하다고 보여집니다.
>       * `belong`과 `color` 컬럼의 용도가 불분명하다고 생각되어 개선이 필요합니다.
>       * 또한 palette 테이블의 변동성에 따라 enum class를 구현할지에 대한 고려해야 할 것 같습니다.
>     * 그룹원 컬러 지정 로직
>       
>       * 위의 고민에서 이어서 기존의 정적 배열 사용하는 방식 or  enum class를 구현하여 사용

enum class를 통해 변경하는 것을 고려한다면 어떤 형태를 생각하고 계실까요?

**Comment by joowojr** [comment]
> > * v1 스키마의 경우 `moim_and_user` 테이블의 `color` 컬럼에 그룹원 고유의 색상을 저장합니다.
> >   
> >   * 이 `color` 컬럼은 palette 테이블을 참조하고 있지 않지만, palette 테이블에 있는 pk 값만(5~14) 저장되도록 구현되어있습니다.
> >   * v2 스키마에는 해당 컬럼이 빠져있는 상태
> > * v2에서의 구현 방향 논의
> >   
> >   * palette 테이블 개선
> >     
> >     * 추후 추가 기능 및 동기화를 위해 해당 테이블이 필요하다고 보여집니다.
> >     * `belong`과 `color` 컬럼의 용도가 불분명하다고 생각되어 개선이 필요합니다.
> >     * 또한 palette 테이블의 변동성에 따라 enum class를 구현할지에 대한 고려해야 할 것 같습니다.
> >   * 그룹원 컬러 지정 로직
> >     
> >     * 위의 고민에서 이어서 기존의 정적 배열 사용하는 방식 or  enum class를 구현하여 사용
> 
> enum class를 통해 변경하는 것을 고려한다면 어떤 형태를 생각하고 계실까요?

저희도 마찬가지고 앞으로의 유지보수를 생각했을 때 palette 테이블에 대한 정보가 코드 상에서도 필요하다고 생각합니다.
palette 테이블에 대해 코드 상에서 식별이 가능하도록 하는 용도로 구현하는 방향으로 생각하고 있습니다.

**Comment by luke0408** [comment]
ㅋㅋㅋ 말이 두번 올라왔네요

**Comment by luke0408** [comment]
그렇다면 현 palette - category의 구조를 다음과 같이 정의해보면 어떨까요?

[ 변경될 구조 ]
color - palette
color - category

- color : 정의한 색상의 이름과 이름에 대한 컬러 값을 저장
- palette : color의 집합
- category : color에 대한 tag 지정

**Comment by joowojr** [comment]
> 그렇다면 현 palette - category의 구조를 다음과 같이 정의해보면 어떨까요?
> 
> [ 변경될 구조 ] color - palette color - category
> 
> * color : 정의한 색상의 이름과 이름에 대한 컬러 값을 저장
> * palette : color의 집합
> * category : color에 대한 tag 지정

각각 테이블로 구성하자는 말씀이실까요?

**Comment by luke0408** [comment]
네네!

**Comment by joowojr** [comment]
> [ 변경될 구조 ] color - palette color - category
> 
> * color : 정의한 색상의 이름과 이름에 대한 컬러 값을 저장
> * palette : color의 집합
> * category : color에 대한 tag 지정

변경될 구조에서는 color-> 현 스키마의 palette와 같은 용도, palette -> 개인화된 color들,  이렇게 이해하면 될까요?
