### ISSUE TITLE
[Feature] 모임 활동 API

### ISSUE THREAD

**Issue by hyeonji91** [Namo-Mongmong/Server#189]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

api v2로 버전 변경

### 기존 모임 활동 이미지 수정 방법
기존 **모든** 이미지 삭제 후 새로 이미지 추가

### 변경안
개인 기록 수정처럼 **추가할 이미지, 삭제할 이미지**를 각각 request로 받는다 
삭제할 이미지가 있으면 개별 삭제하고 추가할 이미지가 있으면 해당되는 이미지만 추가한다

더하여 모임 기록 조회 api에서 img url과 함께 img id도 같이 제공한다

## **Todo**

- [x] 모임 기록 생성 -> [이름 변경] 모임 활동 생성  (실제로 기록이 아니라 활동을 생성하고 있음)
- [ ] 모임 기록 장소 수정 -> [이름 변경] 모임 활동 수정 (이전 명명 규칙을 따르고 있었음)
- [ ] 모임 활동 삭제

**Comment by luke0408** [comment]
이미 이미지 수정 방식은 한 번 수정되지 않았나요?!

**Comment by hosung-222** [comment]
> 이미 이미지 수정 방식은 한 번 수정되지 않았나요?!

모임부분은.. 수정을 못해서 아마 모임부분에서 수정하고 개발하는것 같습니다 ㅎㅎ
