### ISSUE TITLE
[Feature] 개인 페이지 모임 기록 api

### ISSUE THREAD

**Issue by hyeonji91** [Namo-Mongmong/Server#194]
## Type of change

- [x] Feature : 새로운 기능 추가

## **Description**

api v2로 버전 변경

## **Todo**

- [ ] 모임 기록 상세 조회
- [ ] 월간 모임 기록 조회
- [ ] 모임 메모 추가
- [ ] 모임 기록 삭제
