### ISSUE TITLE
[Refactor] 이미지 전달 API DTO들에 ID 값 추가

### ISSUE THREAD

**Issue by hosung-222** [Namo-Mongmong/Server#195]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [X] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 클라이언트 이미지 추적을 위한 Response DTO에 이미지 ID를 추가
  - Images : { "id" : 1, "url" : "s3/123123.jpg"} 형태

## **Todo**

- [x] 일정 기록 월간 조회 API
- [x] 모임 기록 조회 API
- [x] 월간 모임 기록 조회 API
- [x] 모임 기록 상세 조회 API
