### ISSUE TITLE
[Style] DTO 네이밍 수정

### ISSUE THREAD

**Issue by hosung-222** [Namo-Mongmong/Server#197]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [X] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- DTO 네이밍 통일화 및 정리

## **Todo**

- [ ] 컨트롤러 수정
- [ ] DTO 네이밍 수정
