### ISSUE TITLE
[Refactor] 접근 권한 별 auth api 분리

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#228]
## Type of change

- [x] Feature : 새로운 기능 추가
- [x] Refactor : 코드 리팩토링 작업

## **Description**

익명 유저 접근 가능 api와 그렇지 않은 api 분리하기

## **Todo**

- [ ] 권한 별 api 분리
