### ISSUE TITLE
[Feature] 나모 V2 신버전 도메인 매핑

### ISSUE THREAD

**Issue by hosung-222** [Namo-Mongmong/Server#230]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- V2 기획 변경에 따른 도메인 매핑

## **Todo**

- [ ] 기존 도메인 제거
- [ ] 새 도메인 매핑

## **Reference(Optional)**

![image](https://github.com/user-attachments/assets/79c368c7-53a9-46d7-a20a-9dbca4441489)
