### ISSUE TITLE
[Chore] dev 서버 Swagger V1, V2 분리

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#253]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [X] CI/CD : CI/CD 작업 수정
- [X] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

V1, V2 API 에 대한 스웨거를 분리합니다.

## **Todo**

- [x] V1 스웨거 설정
- [x] V2 스웨거 설정
- [x] docker compose 파일 수정
- [ ] nginx 설정 파일 수정
