### ISSUE TITLE
[Refactor] 일정 생성 API / 모임 목록 조회 API 리팩토링

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#268]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [X] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
- 일정 생성 API requst dto 스펙 수정
- 모임 목록 조회 API 
  - 테이블 구조 변경에 따른 API 수정

## **Todo**

- [ ] 일정 생성 API requst dto 스펙 수정
- [ ] Schedule, Participant 엔티티 수정
- [ ] 테이블 구조 변경에 따른 API 수정
