### ISSUE TITLE
[Refactor] 일기 관련 dto 값 수정

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#288]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [X] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [X] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- PallteCode에서 id 반환하도록 변경
- 일기 상단부 스케줄 조회 API에 카테고리{}값 추가

## **Todo**

- [ ] dto 수정
- [ ] converter수정
