### ISSUE TITLE
[Feature] 모임 활동 조회 API 구현

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#295]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 모임 활동을 조회합니다.
<img width="269" alt="image" src="https://github.com/user-attachments/assets/75d69c2e-0922-49b6-ae3c-1cf64a924d5f">

## **Todo**

- [ ] DTO 정의
  - 활동 이름( activityTitle)
  - 활동 참여자 (activityParticipants)
    - 참여자 ID (participantId)
    - 참여자 이름(participantName)
  - 활동 시작 (activityStartDate)
  - 활동 종료 (activityStartDate)
  - 장소 (location)
    - 카카오 장소 ID
    - 장소 이름
  - 총 금액
  - 태그 (tag)
- [ ] 모임 활동 조회 API 구현
- [ ] 정산하기 API 구현

## **Reference(Optional)**

<img width="768" alt="image" src="https://github.com/user-attachments/assets/2db834a6-fac9-4fe0-b44f-2abe3ebce7a9">
<img width="571" alt="image" src="https://github.com/user-attachments/assets/2bc1264a-2156-4a78-a20e-50ee98e5bc85">
