### ISSUE TITLE
[Feature] 요구사항 변경에 따른 모임 일정 수정 API 구현

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#297]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [X] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

-  모임 생성자가 아닌 참여자는 모임의 제목, 사진을 수정할 수 있도록 요구사항이 변경됨
- 이에 따른 참여자용 모임 일정 수정 API 구현 및 관련 비즈니스 로직 수정
- 방장도 커버 이미지 수정이 가능하도록 비즈니스 로직 수정

## **Todo**

- [x] Participant 엔티티 수정
- [x] 참여자용 모임 일정 수정 API 구현
- [x] 모임 일정 조회시 custom image와 title이 조회되도록 수정
