### ISSUE TITLE
[Refactor] Domain 디렉토리 구조 적용

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#3]
## **Issue : Refactoring**

- Global과 Domain 디렉토리 분리

## **Description**

Code Convention에 맞게 Domain 및 Global 디렉토리를 분리한다.

## **Todo**

- [x] Global 디렉토리 분리
  - [x] Config 디렉토리 분리
  - [x] Common 디렉토리 분리
- [x] Domain 디렉토리 분리

## **Reference(Optional)**

- [Namo - Spring Code Convention](https://www.notion.so/mynamo/Spring-Code-Convention-32ab079479504895aa727d86c2a4bae4?pvs=4) 에서 Package 구조 부분 참고
