### ISSUE TITLE
[Bug Fix] 일정 생성 - 일정 참여자 생성 오류

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#304]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
- 회원가입 로직을 수정하면서 participant에 회원의 선호 color가 저장되도록 변경이 덜 된 부분을 수정합니다.

## **Todo**

- 참여자 생성 로직 수정
