### ISSUE TITLE
[Feature] 카테고리 관리 기능 구현

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#307]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 카테고리 관리 기능 구현
  - 카테고리 조회
  - 카테고리 추가
  - 카테고리 편집
  - 카테고리 삭제
  
## **Todo**

- [ ] 카테고리 조회
- [ ] 카테고리 추가
- [ ] 카테고리 편집
- [ ] 카테고리 삭제

## **Reference(Optional)**

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/2a32b0be-d0eb-45b0-bd18-5b3bdb5a0575">
