### ISSUE TITLE
[Feature] 모임 기록/활동 생성 로직 구현

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#311]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 모임 기록 중 활동을 생성하기 위한 API 를 구현합니다.

## **Todo**

- [ ] DTO 명세
  - 활동 참석자
  - 활동 시작
  - 활동 종료
  - 장소 정보
  - 정산 정보
  - 태그
- [ ] 정산 로직 구현
- [ ] 최종 활동 생성 API 구현

## **Reference(Optional)**

<img width="593" alt="image" src="https://github.com/user-attachments/assets/6690cc7e-87e1-412d-add2-440741019306">
<img width="202" alt="image" src="https://github.com/user-attachments/assets/112a33b2-bed4-4879-8c26-470ab31837a1">
