### ISSUE TITLE
[Refactor] TagGenerator 리팩토링

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#316]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [X] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

-TagGenerator 객체 리팩토링으로 유지보수성, 재사용성 향상

## **Todo**

- [ ] TagGenerator 의 태그 생성하는 로직을 분리하여 태그 발급, 중복 체크하는 로직 분리
- [ ] 주요 값 상수처리
