### ISSUE TITLE
[Refactor] 유지보수성 개선

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#318]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [X] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 스웨거 문서 수정
- Random 함수 사용 부분 수정

## **Todo**

- [ ] Reliability 해결
- [ ] Maintainability 해결

## **Reference(Optional)**

<img width="775" alt="image" src="https://github.com/user-attachments/assets/b2137d4e-0bac-4050-81f5-fe945620c6bd">
