### ISSUE TITLE
[Feature] 기록 상단부 스케줄 조회 API에 참여자 정보 추가

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#327]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 기록 상단부 스케줄 조회 API 값에 참여자 정보를 추가합니다.
  - 참석자 명수
  - 참석자 명단 (memberId, Nickname, 로그인/비로그인 여부)
 

## **Todo**

- [ ] DTO 수정
- [ ] Converter 수정

## **Reference(Optional)**

<img width="745" alt="image" src="https://github.com/user-attachments/assets/0c35723b-0060-46c1-acb7-8ad74a35658d">
