### ISSUE TITLE
[Feature] 요구사항 변경에 따른 모임 참여자 수락/비수락 상태 제거

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#331]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
- 모임 생성 시 모임 참여 요청 단계를 생략하고 바로 참여자가 생성되도록 요구사항이 변경되었습니다.
- 그에 따른 테이블 구조 수정 및 로직 수정 작업을 진행합니다.

## **Todo**
- [ ] todo
- [ ] todo
