### ISSUE TITLE
[Refactor] 월간 일정 조회 방식에서 기간을 선택하여 조회하는 방식으로 변경

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#334]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
- 현재 모바일에서 달력을 6주 기준으로 구현되고 있어 월간 조회 방식에서 기간을 직접 지정하여 조회하는 방식으로 변경합니다.

## **Todo**

- [ ] api 쿼리 파라미터 수정
