### ISSUE TITLE
[Feature] 활동 수정 기능 구현

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#341]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

활동 수정하는 기능을 구현합니다.
- 활동 세부 Depth에 대한 내용 수정기능이 포함됩니다.

## **Todo**

- [x] 활동 대주제 수정
  - 활동이름
  - 활동 시작-종료
  - 활동 장소
  - 활동 이미지 
- [ ] 활동 태그 수정
- [x] 활동 참석자 수정
- [ ] 활동 정산 내역 수정

## **Reference(Optional)**

<img width="306" alt="image" src="https://github.com/user-attachments/assets/40198928-d3b4-4803-a865-be5d349300c5">
<img width="308" alt="image" src="https://github.com/user-attachments/assets/4f3a4639-a7f4-4d38-9fc7-12cbd0766c36">
<img width="199" alt="image" src="https://github.com/user-attachments/assets/f6ec21c2-95db-4280-a856-1ab8edca7355">
<img width="203" alt="image" src="https://github.com/user-attachments/assets/ebf770a1-a8a0-4b35-8e07-3a1be204cb06">
