### ISSUE TITLE
[Feature] 전체 정산 조회 기능 구현

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#343]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 모임 스케줄의 전체 활동에 대한 정산 (즉 전체 정산) 기능을 구현합니다.
  - 하나 이상의 활동에 참여한 유저에 대해서만 정산이 활성화 됩니다.

## **Todo**

- [ ] 전체 정산 조회 기능 구현

## **Reference(Optional)**

<img width="325" alt="image" src="https://github.com/user-attachments/assets/2c2c2b3c-d963-426f-92b2-6ad3e608459e">
