### ISSUE TITLE
[Refactor] 일정 시작일/종료일 자료형 변경 리팩토링

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#353]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [X] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
프론트엔드와 협의하여 일정 시작일/ 종료일의 자료형을 Long(unix time) -> Localdatetime으로 형 변환합니다.

## **Todo**

- [ ] request 필드 변환
- [ ] response 필드 변환
