### ISSUE TITLE
[Refactor] 일정 생성 시 위치 정보 null 허용으로 수정

### ISSUE THREAD

**Issue by joowojr** [Namo-Mongmong/Server#380]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
모바일에서의 편리한 dto 처리를 위해 일정 생성 시 위치 정보 null 허용으로 수정합니다.

## **Todo**

- [ ] 개인 일정 생성 수정
- [ ] 모임 일정 생성 수정
