### ISSUE TITLE
[Feature] 친구목록 검색 기능 구현

### ISSUE THREAD

**Issue by hosung-222** [Namo-Mongmong/Server#386]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

친구 검색 기능을 구현합니다.
- 닉네임 & 이름 검색 가능

## **Todo**

- [ ] Controller 명세
- [ ] DTO 구현
- [ ] 검색 로직 구현

## **Reference(Optional)**

<img width="364" alt="image" src="https://github.com/user-attachments/assets/0980e9e7-33f5-4ee1-bf1a-48aff9579cf2">
