### ISSUE TITLE
[Refactor] 기록 캘린더 조회 변경

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#394]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [X] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 기록 캘린더 조회 API 를 변경합니다.
  - 기존 모든 기록에대한 날짜 Return에서 개인 스케줄에 대한 기록과 모임 스케줄에 대한 기록을 분리합니다.
  - 사유 : UI 상 스케줄에 따른 기록의 색깔 차이
  
## **Todo**

- [ ] DTO 재구조화
- [ ] 로직 수정

## **Reference(Optional)**

<img width="204" alt="image" src="https://github.com/user-attachments/assets/d1c19a2b-5a02-4db2-8558-c7e3341628b1">
