### ISSUE TITLE
[Feature] 상대방의 카테고리 정보를 확인하는 기능 구현

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#397]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 상대방의 카테고리 정보를 조회합니다.

## **Todo**

- [ ] 상대방 카테고리 조회
  - [ ] 친구만 조회 가능
  - [ ] 공개 카테고리 여부 확인

## **Reference(Optional)**

<img width="197" alt="image" src="https://github.com/user-attachments/assets/fd58bced-d09d-4c66-b012-e38ffa290abe">
