### ISSUE TITLE
[Feature] 일별 기록 조회에 생일 추가

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#408]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 생일 스케줄 추가에 따른 생일 스케줄 기록 조회를 구현합니다.

## **Todo**

- [ ] dto 변경
- [ ] 로직 수정

## **Reference(Optional)**

<img width="346" alt="image" src="https://github.com/user-attachments/assets/5c2c0b2e-b9e6-47db-9ab2-b28a563a829f">

**Comment by hosunglee222** [comment]
기획 변경으로 해결되었습니다.
