### ISSUE TITLE
[Feature] 모임 기록 캐싱 적용

### ISSUE THREAD

**Issue by hosunglee222** [Namo-Mongmong/Server#413]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 다수의 의해 조회되는 모임 기록에 대해 Redis를 활용한 캐싱기능을 적용합니다.

## **Todo**

- [ ] Redis 설정
- [ ] 캐시 설정
