### ISSUE TITLE
[Feature] 프로필 설정 기능 구현

### ISSUE THREAD

**Issue by hosung-222** [Namo-Mongmong/Server#417]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- Setting Tab 프로필 조회
- 프로필 수정
  - 닉네임 수정
  - 이름 공개/비공개 여부
  - 생년월일 수정
  - 생년월일 공개/비공개 여부
  - 한줄 소개 수정
  - 좋아하는 색깔 수정

## **Todo**

- [ ] 프로필 조회 API 구현
- [ ] 프로필 수정 API 구현

## **Reference(Optional)**

<img width="227" alt="image" src="https://github.com/user-attachments/assets/67d582b6-17d9-44df-98c9-4236a3c928d5">
<img width="466" alt="image" src="https://github.com/user-attachments/assets/9911757d-3da8-419c-a92e-af0390a75284">
