### ISSUE TITLE
[Feature] 사용자 포인트 기능 구현

### ISSUE THREAD

**Issue by hosung-222** [Namo-Mongmong/Server#425]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 사용자 결제를 위한 포인트 추가 및 결제 기능 구현
  - 사용자에 Point 정보 추가
  - 포인트 사용 내역 추가

## **Todo**

- [x] Member point 컬럼 추가
- [x] 사용 내역(PointHistory) 엔티티 구현
- [x] Flyway 적용
- [x] API 개발

## **Reference(Optional)**

<img width="377" alt="image" src="https://github.com/user-attachments/assets/6646c07a-2619-4b82-8a2e-afd61e069683">
<img width="250" alt="image" src="https://github.com/user-attachments/assets/f154f114-5fd8-4ecc-a417-7ee2b125b9c0">
