### ISSUE TITLE
[Feature] 테마샵 기능 구현

### ISSUE THREAD

**Issue by hosung-222** [Namo-Mongmong/Server#427]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 테마샵 관련 기능을 구현합니다.

## **Todo**

- [x] 테마 샵 조회
- [ ] 테마 상세 조회
- [x] 프로필/배경 테마 리스트 조회

## **Reference(Optional)**

<img width="282" alt="image" src="https://github.com/user-attachments/assets/08f361d4-d325-4ab7-9c3f-f6f194551864" />
<img width="603" alt="image" src="https://github.com/user-attachments/assets/bd1bcfd9-bb6f-415e-9adf-d9124957af25" />
<img width="516" alt="image" src="https://github.com/user-attachments/assets/351ac06e-c189-4f7e-9d0b-4bae13157bc1" />
