### ISSUE TITLE
[Refactor] 그룹 참여 API 반환 값 추가

### ISSUE THREAD

**Issue by galug** [Namo-Mongmong/Server#44]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

https://www.notion.so/mynamo/37faed37694749b89ef15e0071365575?p=b25dfa154e064850b47ad0e73ea17745&pm=s
- 그룹 참여 후에 moimId 뿐만이 아니라 그룹 코드까지 반환하게끔 변환한다. 

## **Todo**

- [ ] 그룹 참여 후에 moimId와 그룹 코드를 함께 반환하게 바꾼다.
