### ISSUE TITLE
[Feat] 카테고리 Validation 검증 로직 및 비기능 개발

### ISSUE THREAD

**Issue by galug** [Namo-Mongmong/Server#48]
## Type of change

- [x] Feature : 새로운 기능 추가
- [x] Refactor : 코드 리팩토링 작업

## **Description**

형식적 혹은 논리적 validation 이 필요한 지점을 찾고 이에 대한 검증 처리를 해주겠습니다. 

## **Todo**

- [x] 카테고리
  - [x] 카테고리 생성 : 카테고리의 주인이 생성을 하는지
  - [x] 카테고리 수정 : 카테고리의 주인이 수정을 하는지
  - [x] 카테고리 삭제 : 카테고리의 주인이 삭제를 하는지
    - [x] 카테고리 삭제 시 기본 카테고리가 삭제 되지 않게끔 유지 
    - [x] 모임 스케줄 생성시 모임 스케줄이 들어가게끔 변경
