### ISSUE TITLE
[Feat] 모임 Validation 검증 로직 및 비기능 개발

### ISSUE THREAD

**Issue by galug** [Namo-Mongmong/Server#49]
## Type of change

- [x] Feature : 새로운 기능 추가
- [x] Refactor : 코드 리팩토링 작업

## **Description**

형식적 혹은 논리적 validation 이 필요한 지점을 찾고 이에 대한 검증 처리를 해주겠습니다. 

## **Todo**

- [x] 모임
  - [x] 모임 생성: 모임 생성 시에 img 가 null 값이면 기본 이미지가 들어가게 수정 
  - [x] 모임 이름 변경: 모임 이름 변경에 대한 형식적 검증 로직 추가
  - [x] 모임 참여: 모임 참여 시에 모임원과 색깔이 같은 문제 해결 
  - [x] 모임 탈퇴: 모임 참여자 본인이 탈퇴를 진행하는지에 대한 검증
