### ISSUE TITLE
[Refactor] Category Domain Refactoring

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#5]
## **Issue : Refactoring**

Category Domain에 대한 리펙토링을 진행합니다.

## **Description**

Code Convention에 맞게 Category Domain을 변경한다. 

## **Todo**

- [x] presentation 계층 분리 : ui 디렉토리를 사용하여 구현
- [x] application 계층 분리
- [x] Persistence 계층 분리 : dao 디렉토리를 사용하여 구현
- [x] domain model 분리
- [x] Facade 적용

## **Reference(Optional)**

- [Namo - Spring Code Convention](https://www.notion.so/mynamo/Spring-Code-Convention-32ab079479504895aa727d86c2a4bae4?pvs=4) 에서 [내부 구조 - Domain Package] 부분 참고
