### ISSUE TITLE
[CI/CD] 수동 배포용 Docker file 작성

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#53]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [x] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

수동 배포를 위한 Docker File을 작성한다

## **Todo**

- [x] docker file 작성
- [x] docker hub push, pull test
- [x] docker image run test
