### ISSUE TITLE
[Feat] 모임 스케줄 Validation 검증 로직 및 비기능 개발

### ISSUE THREAD

**Issue by galug** [Namo-Mongmong/Server#55]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Refactor : 코드 리팩토링 작업

## **Description**

형식적 혹은 논리적 validation 이 필요한 지점을 찾고 이에 대한 검증 처리를 해주겠습니다. 

## **Todo**

- [x] 모임 스케줄 
  - [x] 모임 스케줄 생성: 모임 안에 포함된 사람이 모임 스케줄을 추가하는지 검증 
    - [x] 모임 스케줄 생성 시에 모임 스케줄 유저가 아무도 없으면 안됨... 
    - [x] 모임원이 아닌 사람이 스케줄에 추가가 되어 있으면 안됨 
    - [x] 모임 카테고리가 없는 사람에 대해서 모임 스케줄 유저가 생성되면 안되는 걸 검증 
  - [x] 모임 스케줄 수정: 모임 안에 포함된 사람이 모임 스케줄을 수정하는지 검증
    - [x] 모임 스케줄 수정  시에 모임 스케줄 유저가 아무도 없으면 안됨...   
    - [x] 모임원이 아닌 사람이 스케줄에 수정이 되면 안됨 
  - [x] 모임 스케줄 삭제: 모임 안에 포함된 사람이 모임 스케줄을 삭제하는지 검증  
  - [x] 모임 스케줄 조회
    - [x] 모임스케줄 형식에 대한 검증  
    - [x] 모임에 속한 유저인지 검증
