### ISSUE TITLE
[CI/CD] 개발환경 cicd 구축

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#58]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [x] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

Github action + docker hub + ECR + ECS 을 사용한 개발환경 CICD 파이프라인 구축

## **Todo**

- [x] 환경 구축
  - [x] ECR 설정
  - [x] ECS 설정
- [ ] action 구축
  - [x] CI action 구축
  - [ ] CD action 구축
- [ ] 배포 test

## **Reference(Optional)**

- https://velog.io/@woohobi/3.-%EB%8F%84%EC%BB%A4%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-beanstalk-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0-with-Github-Actions
