### ISSUE TITLE
[Feat] 그룹 관련 요구 사항 및 디버깅 작업 

### ISSUE THREAD

**Issue by galug** [Namo-Mongmong/Server#61]
## Type of change

- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업

## **Description**

프론트에서 넘어온 요구사항들을 처리하겠습니다.

## **Todo**

- [ ] page_size 지정 사이즈로 고정해서 클라이언트에게 넘겨주게 변경 
- [ ] 그룹에 참여한 날짜를 기준으로 그룹 리스트 sorting
- [ ] 그룹 일정 조회시 어떤 그룹인지 확인하는 방법 추가
- [ ] 모임 기록 삭제 API 추가
