### ISSUE TITLE
[Fix] Layered jar docker file build 과정시 발생하는 오류 해결

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#68]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

docker file run시 JarLauncher 관련 에러 발생

## **Todo**

- [x] JarLauncher 에러 해결
