### ISSUE TITLE
[Feature] 전체 모임 스케줄 response 조정 및 모임 API 문제 조정

### ISSUE THREAD

**Issue by galug** [Namo-Mongmong/Server#74]
## Type of change

- [ ] Refactor : 코드 리팩토링 작업
- [ ]  Bug fix : 버그 수정

## **Description**

response 에 대한 변경이 필요합니다. 

## **Todo**

- [x] 모임 조회 API에서 수정된 네임을 반환하지 않는 문제

## **Reference(Optional)**

https://www.notion.so/mynamo/response-76fbd845a37141a184650fbd1a61513f
