### ISSUE TITLE
[Feature] 일정 validation처리

### ISSUE THREAD

**Issue by hyeonji91** [Namo-Mongmong/Server#75]
## Type of change

- [x] Feature : 새로운 기능 추가

## **Description**

일정 validation처리

## **Todo**

- [x] 개인쪽에서 모임 스케줄 삭제시 개인캘린더에서만 모임스케줄이 안보이게 (해당 모임스케줄에는 개인이 포함되어있음)
- [x] 스케줄 추가시 본인의 카테고리인지 검증
- [x] 시작 날짜가 종료 날짜 전인지 검사
- [x] 알람 값 0, 5, 10, 30, 60 만 허용
