### ISSUE TITLE
[Bug] 신규 유저 생성시 status 칼럼이 null로 들어오는 문제 해결

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#79]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

신규 유저 생성시 userConverter에서 생성된 신규 유저 객체의 status 값이 null이라 생기는 문제 해결

## **Todo**

- [x] 에러 픽스
