### ISSUE TITLE
[Refactor] Moim Domain Refactoring

### ISSUE THREAD

**Issue by galug** [Namo-Mongmong/Server#8]
## Issue : Refactoring
Moim Domain에 대한 리펙토링을 진행합니다.

## Description
Code Convention에 맞게 Moim Domain을 변경한다.

## Todo
- [x] #13
- [x] application 계층 분리
- [x] Persistence 계층 분리 : dao 디렉토리를 사용하여 구현
- [x] domain model 분리
- [x] Facade 적용

## Reference(Optional)
- [Namo - Spring Code Convention](https://www.notion.so/mynamo/Spring-Code-Convention-32ab079479504895aa727d86c2a4bae4?pvs=4) 에 맞춰서 작성
