### ISSUE TITLE
[Feature] Swagger api test 환경 설정

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#90]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [x] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

프론트 개발자들이 swagger를 통해 api test를 진행할 수 있도록 환경을 구축한다

## **Todo**

- [x] swagger에서 https url를 사용할 수 있도록 변경한다.
- [x] swagger에서 토큰 정보를 사용할 수 있도록 변경한다.
