### ISSUE TITLE
[Feature] Api 버저닝 준비 및 api url 수정

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#92]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [x] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- api url에 api/v1 추가
- 도메인명 명시를 위한 분리

## **Todo**

- [ ] api url path 변경
- [ ] api 버전 명시
- [ ] 스웨거 api 그룹 정리
