### ISSUE TITLE
[Refactor] 도메인 구조 변경

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#94]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

기존의 도메인 구조를 아래의 2개로 변경
- 개인 : Schedule, diary, category
- 그룹 : 그룹, 그룹 일정, 그룹 기록
- 기타 : 인증, 약관

## **Todo**

- [x] 개인 도메인 구조 설정
- [x] 그룹 도메인 구조 설정
- [x] 기타 도메인 구조 설정
