### ISSUE TITLE
[Refactor] Request & Response 파라미터명 변경

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#97]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

변경된 도메인 구조 및 명명 규칙에 맞게 Request 및 Response 파라미터 변경

## **Todo**

- [x] Request 파라미터 변경
- [x] Response 파라미터 변경
- [x] 스웨거에서 변경된 파라미터를 확인할 수 있도록 적용
