### ISSUE TITLE
[Feature] 날짜별 모임 일정 조회 마라미터 추가

### ISSUE THREAD

**Issue by luke0408** [Namo-Mongmong/Server#98]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

[프론트 요구 사항]
날짜별 모임 일정을 표시할 때 기록 여부에 따라 오른쪽 뷰가 바뀝니다.
모임 기록이 없을 때 (그룹에서 모임 기록 추가를 안했을 때) -> 아이콘 X
모임 기록은 있지만, 개인의 모임 메모가 비어있을 때 -> 아이콘 회색
모임 기록도 있고, 개인의 모임 메모도 썼을 때 -> 아이콘 주황색

그런데 현재 개인의 모임 메모 존재 여부 판단을 위해서 
날짜별 모임 일정을 조회할 때 "월별" 모임 기록을 조회해서 맞는 id를 찾은 후 모임 메모를 확인합니다.

월별을 모두 조회해서 너무 무겁고
기록 월별 조회는 페이징이 되어있어서 여기서 쓰기 곤란합니다.

그래서 기존 hasDiary이 Int로 0, 1 로 사용 중인데
"모임 일정에서만" null, 0, 1 로 상태 3개를 처리하도록 수정요청

## **Todo**

- [ ] 반환 값에 상태값 추가

**Comment by luke0408** [comment]
#109 이슈로 매실에게 작업 위임함으로써 close
